//go:build ignore

package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	if _, err := os.Stat("version_gen.go"); err == nil {
		return
	}

	v := "dev"
	if out, err := exec.Command("git", "describe", "--tags", "--abbrev=0").Output(); err == nil {
		v = strings.TrimSpace(string(out))
	}

	code := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage version\n\nvar gitVersion = %q\n", v)
	if err := os.WriteFile("version_gen.go", []byte(code), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
