//go:build ignore

package main

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
)

func main() {
	v := "dev"
	if out, err := exec.Command("git", "describe", "--tags", "--abbrev=0").Output(); err == nil {
		v = strings.TrimSpace(string(out))
	}

	if data, err := os.ReadFile("version_gen.go"); err == nil {
		re := regexp.MustCompile(`var gitVersion = "(.*)"`)
		if m := re.FindSubmatch(data); len(m) == 2 && string(m[1]) == v {
			return
		}
	}

	code := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage version\n\nvar gitVersion = %q\n", v)
	if err := os.WriteFile("version_gen.go", []byte(code), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("version: %s\n", v)
}
